input_template:
  '{

    "## Sample attributes": "",
    "merge_rnaseq_samples_wf.sample_names": "<<<IMPORT_WF_LABEL>>> cromwell-sample-label",
    "merge_rnaseq_samples_wf.derpity": "<<<IMPORT_WF_INPUT>>> rnaseq_pe_wf.read_len",
    "merge_rnaseq_samples_wf.sample_names_from_inputs": "<<<IMPORT_WF_INPUT>>> rnaseq_pe_wf.sample_name",
    "merge_rnaseq_samples_wf.multiqc_input_dirs": "<<<IMPORT_WF_OUTPUT>>> rnaseq_pe_wf.multiqc_input_dir",
    "merge_rnaseq_samples_wf.salmon_quant_dirs": "<<<IMPORT_WF_OUTPUT>>> rnaseq_pe_wf.salmon_quant_dir"

  }'

sample_id_col: merge_rnaseq_samples_wf.sample_names

sample_sheet_validators: [validate_ss_against_wdl_template]

wf_type: gather