input_template:
  '{

    "## Sample attributes": "",
    "merge_rnaseq_samples_wf.sample_names": "$$$cromwell-sample-label",
    "merge_rnaseq_samples_wf.sample_batch_names": "$$$cromwell-batch-sample-label",
    "merge_rnaseq_samples_wf.multiqc_input_dirs": "@@@rnaseq_pe_wf.multiqc_input_dir",
    "merge_rnaseq_samples_wf.salmon_quant_dirs": "@@@rnaseq_pe_wf.salmon_quant_dir",
    "merge_rnaseq_samples_wf.dummy": 2

  }'

sample_id_col: rnaseq_pe_wf.sample_name

sample_sheet_validators: [validate_ss_against_wdl_template]

wf_type: gather